AWSTemplateFormatVersion: 2010-09-09

Parameters:
  StackExportPrefix:
    Type: "String"
    Default: "project-dev-t2"
  pEnvironment:
    Type: "String"
    Default: "dev"
  pPublisherAccountID:
    Type: "String"
    Default: "956976708961"

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Retain"
    Properties:
      BucketName: !Sub "${StackExportPrefix}-bucket-${pPublisherAccountID}"
      AccessControl: "Private"
      VersioningConfiguration:
        Status: "Enabled"
      LifecycleConfiguration:
        Rules:
          - Id: "S3BucketArchive"
            Status: "Enabled"
            ExpirationInDays: '365' # Complete Disposal/Deletion of Data after 1 year
            Transition:
              TransitionInDays: '60' # Move Data from S3 bucket to Infrequent Archive after 60 days.
              StorageClass: GLACIER

  S3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: IAMPolicyS3BucketPolicy
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
              - s3:DeleteObject
              - s3:GetObjectVersion
              - s3:DeleteObjectVersion
              - s3:AbortMultipartUpload
              - s3:ListMultipartUploadParts
              - s3:GetBucketLocation
              - s3:ListBucketVersions
            Resource:
              - !Sub "arn:aws:s3:::${S3Bucket}"
              - !Sub "arn:aws:s3:::${S3Bucket}/*"
            Principal:
              AWS: [ !Ref pPublisherAccountID ]


Outputs:
  S3Bucket:
    Description: "S3Bucket Bucket Name"
    Value: !Ref S3Bucket
