AWSTemplateFormatVersion: '2010-09-09'
Description: Create an IAM Permissions Boundary Policy

Parameters:
  StackExportPrefix:
    Type: "String"
    Default: "project-dev-t2"
  pEnvironment:
    Type: "String"
    Default: "dev"

Resources:
  PermissionsBoundary:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${StackExportPrefix}-PermissionsBoundary"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Deny
            Action: '*'
            Resource: '*'
          - Sid: AllowLogsPolicy
            Effect: Allow
            Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:DescribeLogGroups'
              - 'logs:DescribeLogStreams'
              - 'logs:PutLogEvents'
            Resource: '*'
          - Sid: AllowS3Policy
            Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:ListBucket'
              - 's3:DeleteObject'
              - 's3:GetObjectVersion'
              - 's3:DeleteObjectVersion'
              - 's3:AbortMultipartUpload'
              - 's3:ListMultipartUploadParts'
              - 's3:GetBucketLocation'
              - 's3:ListBucketVersions'
            Resource: '*'
          - Sid: AllowEC2Policy
            Effect: Allow
            Action:
              - 'ec2:DescribeInstances'
              - 'ec2:DescribeTags'
              - 'ec2:TerminateInstances'
            Resource: '*'

Outputs:
  PermissionsBoundary:
    Description: The ARN of the Permissions Boundary Policy
    Value: !Ref PermissionsBoundary
    Export:
      Name: !Sub "${StackExportPrefix}-PermissionsBoundary"
