AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Database stack creation prerequisite:
  - RDS Security Group

Parameters:
  StackExportPrefix:
    Type: "String"
    Default: "project-dev-t2"
  pEnvironment:
    Type: "String"
    Default: "dev"
  pResourceName:
    Type: String
    Default: "RDSDC"
    AllowedPattern: "[A-Za-z0-9]*"
  DatabaseName:
    Type: "String"
    Description: "Database name"
    MinLength: '1'
    MaxLength: '30'
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: "Name must begin with a letter and contain only alphanumeric characters."
    Default: "MyDatabase"
  DatabaseUser:
    NoEcho: 'true'
    Type: "String"
    Description: "Database admin account name"
    MinLength: '5'
    MaxLength: '16'
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: "Name must begin with a letter and contain only alphanumeric characters."
    Default: "MyDatabase123"
  DatabasePassword:
    NoEcho: 'true'
    Type: "String"
    Description: "Database admin account password"
    MinLength: '6'
    MaxLength: '41'
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: "Password must contain only alphanumeric characters."
    Default: "MyDatabase123"
  DatabaseSize:
    Type: "String"
    Description: "Database storage size in gigabytes (GB)"
    MinLength: '1'
    AllowedPattern: "[5-9][0-9]*"
    ConstraintDescription: "Enter a size of at least 5 GB"
    Default: "5"

  DatabaseEngine:
    Type: "String"
    Description: "Database engine, MySQL or PostgreSQL"
    ConstraintDescription: "Choose an engine from the drop down"
    Default: "aurora-mysql"
    AllowedValues:
      - "aurora-mysql"

  DatabaseFamily:
    Type: "String"
    Description: "Database engine, DatabaseFamily"
    ConstraintDescription: "Choose an engine from the drop down"
    Default: "aurora-mysql8.0"
    AllowedValues:
      - "aurora-mysql8.0"

  ## :: InfraStack Resource
  # NOTE : If this template is attached to InfraStack, then replace the following:
  # Fn::ImportValue: !Sub "${StackExportPrefix}-${VPC}" -> !Ref VPC
  # Fn::ImportValue: !Sub "${StackExportPrefix}-${PrivateSubnets}" -> !Ref Subnets

  VPC:
    Type: String
    Default: "VPC"
  Subnets:
    Type: String
    Default: "PrivateSubnets"
  SGDBInstance:
    Type: String
    Default: "RDatabaseSG"

####### Condition Setup #######
Conditions:
  isProd: !Equals [ !Ref pEnvironment, "prod" ]

Resources:
  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub "${pEnvironment} RDS DB subnet group"
      SubnetIds: !Split [ ",", Fn::ImportValue: !Sub  "${StackExportPrefix}-${Subnets}" ]


  DBClusterParameterGroup:
    Type: "AWS::RDS::DBClusterParameterGroup"
    Properties:
      Description: "CloudFormation Sample Aurora Cluster Parameter Group"
      Family: !Ref DatabaseFamily
      Parameters:
        time_zone: "UTC"
        collation_connection: "utf8_general_ci"
        character_set_database: "utf8"

  DatabaseCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBSubnetGroupName: !Ref DbSubnetGroup
      VpcSecurityGroupIds:
        - Fn::ImportValue: !Sub "${StackExportPrefix}-SG-${SGDBInstance}"
      Engine: !Ref DatabaseEngine
      MasterUsername: !Ref DatabaseUser
      MasterUserPassword: !Ref DatabasePassword
      DBClusterParameterGroupName: !Ref DBClusterParameterGroup
      DBClusterIdentifier: !Sub "${StackExportPrefix}-db-cluster"
      StorageEncrypted: 'true'
      BackupRetentionPeriod: '3'
      PreferredBackupWindow: '12:00-13:00'
      PreferredMaintenanceWindow: 'mon:13:00-mon:14:00'

Outputs:
  DbSubnetGroup:
    Description: "RDS DB subnet group"
    Value: !Ref DbSubnetGroup
    Export:
      Name: !Sub "${StackExportPrefix}-${pResourceName}-DbSubnetGroup"

  Database:
    Description: "RDS Database ID"
    Value: !Ref DatabaseCluster
    Export:
      Name: !Sub "${StackExportPrefix}-${pResourceName}-Database"

  DatabaseName:
    Description: "RDS Database Name"
    Value: !Ref DatabaseName
    Export:
      Name: !Sub "${StackExportPrefix}-${pResourceName}-DatabaseName"

  DatabaseEndpoint:
    Description: "RDS Database Endpoint"
    Value: !GetAtt DatabaseCluster.Endpoint.Address
    Export:
      Name: !Sub "${StackExportPrefix}-${pResourceName}-DatabaseEndpoint"

  DatabaseReadEndpoint:
    Description: "RDS Database Endpoint"
    Value: !GetAtt DatabaseCluster.ReadEndpoint.Address
    Export:
      Name: !Sub "${StackExportPrefix}-${pResourceName}-DatabaseReadEndpoint"

  DatabaseUser:
    Description: "RDS Database admin account user"
    Value: !Ref DatabaseUser
    Export:
      Name: !Sub "${StackExportPrefix}-${pResourceName}-DataPrivateSubnets"

  DatabasePassword:
    Description: "RDS Database admin account password"
    Value: !Ref DatabasePassword
    Export:
      Name: !Sub "${StackExportPrefix}-${pResourceName}-DatabaseUser"